#ifndef CELLAB_CELL_KINDS_HPP_INCLUDED
#   define CELLAB_CELL_KINDS_HPP_INCLUDED

enum CELL_KIND
{
    EXCITATORY_LOCAL_NEURON = 0,
    EXCITATORY_PROJECTION_NEURON,
    INHIBITORY_LOCAL_NEURON,

    NUM_KINDS_OF_CELLS
};

unsigned char num_cell_kinds();

#endif
